import 'package:drift/drift.dart';
import 'database.dart';

/// Container for session template and its exercises
class OlySessionSeed {
  final OlySessionTemplatesCompanion template;
  final List<OlySessionExercisesCompanion> exercises;

  OlySessionSeed({required this.template, required this.exercises});
}

/// Get all OLY exercise types
List<OlyExerciseTypesCompanion> getOlyExerciseTypesSeed() {
  return [
    OlyExerciseTypesCompanion.insert(
      id: 'static',
      name: 'Static reversals',
      description: Value('Simple hold with elbow sling. Fingertips should just touch the string.'),
      intensity: const Value(1.0),
      category: const Value('static'),
      firstIntroducedAt: const Value('1.0'),
      sortOrder: const Value(1),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'extend_front',
      name: 'Extend front',
      description: Value('Push front end forward towards target and hold.'),
      intensity: const Value(1.1),
      category: const Value('movement'),
      firstIntroducedAt: const Value('1.0'),
      sortOrder: const Value(2),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'back_end_movement',
      name: 'Back end movement',
      description: Value('Move string end back and forth slightly. Movement comes from elbow. 1cm each way.'),
      intensity: const Value(1.3),
      category: const Value('movement'),
      firstIntroducedAt: const Value('1.1'),
      sortOrder: const Value(3),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'extend_front_movement',
      name: 'Extend front movement',
      description: Value('Push front end towards target, then relax back and push forward again.'),
      intensity: const Value(1.15),
      category: const Value('movement'),
      firstIntroducedAt: const Value('1.3'),
      sortOrder: const Value(4),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'long_hold',
      name: 'Long hold',
      description: Value('Stay at full draw as long as possible. Try to maintain form and posture. Shaking is fine but come down once collapsing.'),
      intensity: const Value(1.0),
      category: const Value('hold'),
      firstIntroducedAt: const Value('1.5'),
      sortOrder: const Value(5),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'full_front_extension',
      name: 'Full front extension',
      description: Value('Push front end as far forward as you can and hold.'),
      intensity: const Value(1.15),
      category: const Value('movement'),
      firstIntroducedAt: const Value('1.6'),
      sortOrder: const Value(6),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'fast_movement_both',
      name: 'Fast movement both sides',
      description: Value('Pump both ends to move quickly. Big movements from crunched in to full extension. Try to maintain line.'),
      intensity: const Value(1.1),
      category: const Value('movement'),
      firstIntroducedAt: const Value('2.0'),
      sortOrder: const Value(7),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'slow_movement',
      name: 'Slow movement',
      description: Value('Controlled slow movement as prescribed.'),
      intensity: const Value(1.2),
      category: const Value('movement'),
      firstIntroducedAt: const Value('2.2'),
      sortOrder: const Value(8),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'front_expansion_aimed',
      name: 'Front end expansion aimed',
      description: Value('Using sight pin, expand off front keeping sight pin on fixed point.'),
      intensity: const Value(1.25),
      category: const Value('aimed'),
      firstIntroducedAt: const Value('2.5'),
      sortOrder: const Value(9),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'back_expansion_aimed',
      name: 'Back end expansion aimed',
      description: Value('Expand on back end, while maintaining front end fixed on aiming point.'),
      intensity: const Value(1.4),
      category: const Value('aimed'),
      firstIntroducedAt: const Value('2.5'),
      sortOrder: const Value(10),
    ),
    OlyExerciseTypesCompanion.insert(
      id: 'both_sides_expansion_aimed',
      name: 'Both sides expansion aimed',
      description: Value('Expand both ends while maintaining aim.'),
      intensity: const Value(1.45),
      category: const Value('aimed'),
      firstIntroducedAt: const Value('2.5'),
      sortOrder: const Value(11),
    ),
  ];
}

/// Get all OLY session templates with their exercises
List<OlySessionSeed> getOlySessionTemplatesSeed() {
  return [
    _session10(),
    _session11(),
    _session12(),
    _session13(),
    _session14(),
    _session15(),
    _session16(),
    _session17(),
    _session18(),
    _session19(),
    _session20(),
    _session21(),
    _session22(),
    _session23(),
    _session24(),
    _session25(),
  ];
}

// =============================================================================
// SESSION 1.0 - Intro
// =============================================================================
OlySessionSeed _session10() {
  const sessionId = 'session_1.0';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.0',
      name: 'Session 1.0',
      focus: const Value('Intro'),
      durationMinutes: 15,
      volumeLoad: 16492,
      adjustedVolumeLoad: 16758,
      workRatio: 0.539,
      adjustedWorkRatio: 0.548,
      requirements: const Value('Nil'),
      notes: const Value('First session, attempt to stick to times. Look forward, not towards bow.'),
      sortOrder: const Value(10),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 5,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('Draw elbow behind, front arm extended'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 5,
        workSeconds: 15,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front',
        exerciseOrder: 3,
        reps: 5,
        workSeconds: 10,
        restSeconds: 20,
        details: const Value('Push draw arm forward as far as possible, maintain posture'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 5,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 10,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 6,
        reps: 1,
        workSeconds: 30,
        restSeconds: 0,
        details: const Value('Hold as long as you can while maintaining posture'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.1 - Into and beginning of movement
// =============================================================================
OlySessionSeed _session11() {
  const sessionId = 'session_1.1';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.1',
      name: 'Session 1.1',
      focus: const Value('Into and beginning of movement'),
      durationMinutes: 14,
      volumeLoad: 15960,
      adjustedVolumeLoad: 16838,
      workRatio: 0.550,
      adjustedWorkRatio: 0.581,
      requirements: const Value('Be comfortable with S.1'),
      notes: const Value('Strap length tip of fingers at full draw. Look forward, not towards bow.'),
      sortOrder: const Value(11),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 3,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('Draw elbow behind, front arm extended'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 10,
        restSeconds: 20,
        details: const Value('Push draw arm forward as far as possible, maintain posture'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 5,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 10,
        restSeconds: 20,
        details: const Value('2x5s. Slide back end 1cm behind and 1cm in front of anchor'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 3,
        workSeconds: 10,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 7,
        reps: 3,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('2x5s push front arm forward in steady movement for 5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 8,
        reps: 1,
        workSeconds: 30,
        restSeconds: 0,
        details: const Value('Hold as long as you can while maintaining posture'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.2 - Increasing hold time
// =============================================================================
OlySessionSeed _session12() {
  const sessionId = 'session_1.2';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.2',
      name: 'Session 1.2',
      focus: const Value('Increasing hold time'),
      durationMinutes: 15,
      volumeLoad: 17556,
      adjustedVolumeLoad: 18753,
      workRatio: 0.588,
      adjustedWorkRatio: 0.628,
      requirements: const Value('Minimum 1 week work'),
      notes: const Value('Be comfortable with S.2. Strap length tip of fingers at full draw.'),
      sortOrder: const Value(12),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 3,
        workSeconds: 12,
        restSeconds: 25,
        details: const Value('Draw elbow behind, front arm extended'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 3,
        workSeconds: 18,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
        details: const Value('Push draw arm forward as far as possible, maintain posture'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 5,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 10,
        restSeconds: 20,
        details: const Value('2x5s. Slide back end 1cm behind and 1cm in front of anchor'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 3,
        workSeconds: 10,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 7,
        reps: 3,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('2x5s. Push front arm forward in steady movement for 5s'),
        intensityOverride: const Value(1.3),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 8,
        reps: 1,
        workSeconds: 30,
        restSeconds: 1,
        details: const Value('Hold as long as you can while maintaining posture'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.3 - Slight increase of intensity
// =============================================================================
OlySessionSeed _session13() {
  const sessionId = 'session_1.3';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.3',
      name: 'Session 1.3',
      focus: const Value('Slight increase of intensity'),
      durationMinutes: 20,
      volumeLoad: 21812,
      adjustedVolumeLoad: 23248,
      workRatio: 0.519,
      adjustedWorkRatio: 0.553,
      requirements: const Value('Not be too tired with S1.2'),
      sortOrder: const Value(13),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 4,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('Draw elbow behind, front arm extended'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 4,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 10,
        restSeconds: 20,
        details: const Value('Push draw arm forward as far as possible, maintain posture'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 6,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 4,
        workSeconds: 10,
        restSeconds: 20,
        details: const Value('2x5s slide back end 1cm behind and 1cm in front of anchor'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 4,
        workSeconds: 10,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 7,
        reps: 4,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('2x5s Push front arm forward in steady movement for 5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 8,
        reps: 4,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('Draw elbow behind, front arm extended'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 9,
        reps: 1,
        workSeconds: 30,
        restSeconds: 0,
        details: const Value('Hold as long as you can while maintaining posture'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.4 - Both sides movement
// =============================================================================
OlySessionSeed _session14() {
  const sessionId = 'session_1.4';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.4',
      name: 'Session 1.4',
      focus: const Value('Both sides movement'),
      durationMinutes: 20,
      volumeLoad: 24046,
      adjustedVolumeLoad: 25563,
      workRatio: 0.598,
      adjustedWorkRatio: 0.636,
      requirements: const Value('Minimum 3 weeks work'),
      notes: const Value('Be comfortable with S.2'),
      sortOrder: const Value(14),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 4,
        workSeconds: 12,
        restSeconds: 25,
        details: const Value('Draw elbow behind, front arm extended'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 4,
        workSeconds: 18,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
        details: const Value('Push draw arm forward as far as possible, maintain posture'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 5,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 4,
        workSeconds: 10,
        restSeconds: 20,
        details: const Value('2x5s. Slide back end 1cm behind and 1cm in front of anchor'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 3,
        workSeconds: 10,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 7,
        reps: 4,
        workSeconds: 10,
        restSeconds: 25,
        details: const Value('2x5s Push front arm forward in steady movement for 5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 8,
        reps: 4,
        workSeconds: 18,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 9,
        reps: 1,
        workSeconds: 30,
        restSeconds: 1,
        details: const Value('Hold as long as you can while maintaining posture'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.5 - Increased holds
// =============================================================================
OlySessionSeed _session15() {
  const sessionId = 'session_1.5';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.5',
      name: 'Session 1.5',
      focus: const Value('Increased holds'),
      durationMinutes: 16,
      volumeLoad: 19684,
      adjustedVolumeLoad: 21480,
      workRatio: 0.654,
      adjustedWorkRatio: 0.713,
      requirements: const Value('Minimum 3 weeks'),
      notes: const Value('Work towards front shoulder closer in line to front of body'),
      sortOrder: const Value(15),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 3,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 2,
        workSeconds: 10,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
        details: const Value('Push arm forward 3x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 2,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
        details: const Value('1cm each way 3x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 2,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 7,
        reps: 3,
        workSeconds: 15,
        restSeconds: 30,
        details: const Value('Front arm forward 3x5s'),
        intensityOverride: const Value(1.3),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 8,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 9,
        reps: 1,
        workSeconds: 30,
        restSeconds: 1,
        details: const Value('As long as you can'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.6 - Increasing hold time/front end
// =============================================================================
OlySessionSeed _session16() {
  const sessionId = 'session_1.6';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.6',
      name: 'Session 1.6',
      focus: const Value('Increasing hold time/front end'),
      durationMinutes: 17,
      volumeLoad: 21280,
      adjustedVolumeLoad: 22916,
      workRatio: 0.630,
      adjustedWorkRatio: 0.678,
      requirements: const Value('S.2 done minimum twice'),
      sortOrder: const Value(16),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 5,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 5,
        workSeconds: 10,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'full_front_extension',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
        details: const Value('Hold front arm as far as possible'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 3,
        workSeconds: 10,
        restSeconds: 15,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 2,
        workSeconds: 10,
        restSeconds: 10,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 6,
        reps: 2,
        workSeconds: 20,
        restSeconds: 30,
        details: const Value('4x5s'),
        intensityOverride: const Value(1.3),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 7,
        reps: 4,
        workSeconds: 10,
        restSeconds: 15,
        details: const Value('2x5s'),
        intensityOverride: const Value(1.3),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 8,
        reps: 5,
        workSeconds: 15,
        restSeconds: 25,
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.7 - Increasing volume
// =============================================================================
OlySessionSeed _session17() {
  const sessionId = 'session_1.7';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.7',
      name: 'Session 1.7',
      focus: const Value('Increasing volume'),
      durationMinutes: 21,
      volumeLoad: 26600,
      adjustedVolumeLoad: 28396,
      workRatio: 0.649,
      adjustedWorkRatio: 0.692,
      notes: const Value('Work towards front shoulder closer in line to front of body'),
      sortOrder: const Value(17),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 4,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 2,
        workSeconds: 10,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
        details: const Value('Push arm forward 3x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 2,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 4,
        workSeconds: 15,
        restSeconds: 25,
        details: const Value('1cm each way 3x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 2,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 7,
        reps: 4,
        workSeconds: 15,
        restSeconds: 30,
        details: const Value('Front arm forward 3x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 8,
        reps: 3,
        workSeconds: 15,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 9,
        reps: 4,
        workSeconds: 20,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_10',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 10,
        reps: 1,
        workSeconds: 30,
        restSeconds: 1,
        details: const Value('As long as you can'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.8 - Work ratio increase
// =============================================================================
OlySessionSeed _session18() {
  const sessionId = 'session_1.8';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.8',
      name: 'Session 1.8',
      focus: const Value('Work ratio increase'),
      durationMinutes: 20,
      volumeLoad: 31920,
      adjustedVolumeLoad: 31920,
      workRatio: 1.042,
      adjustedWorkRatio: 1.042,
      requirements: const Value('30 minute work load'),
      notes: const Value('Work towards front shoulder closer in line to front of body'),
      sortOrder: const Value(18),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 8,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 3,
        workSeconds: 30,
        restSeconds: 27,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 3,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
      ),
    ],
  );
}

// =============================================================================
// SESSION 1.9 - Volume load increase
// =============================================================================
OlySessionSeed _session19() {
  const sessionId = 'session_1.9';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '1.9',
      name: 'Session 1.9',
      focus: const Value('Volume load increase'),
      durationMinutes: 27,
      volumeLoad: 44688,
      adjustedVolumeLoad: 44688,
      workRatio: 1.119,
      adjustedWorkRatio: 1.119,
      requirements: const Value('30 minute work load'),
      notes: const Value('Work towards front shoulder closer in line to front of body'),
      sortOrder: const Value(19),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 10,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 3,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 3,
        reps: 5,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 3,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 5,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 6,
        reps: 1,
        workSeconds: 60,
        restSeconds: 1,
        details: const Value('Hold as long as you can'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 2.0 - 30 minute session
// =============================================================================
OlySessionSeed _session20() {
  const sessionId = 'session_2.0';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '2.0',
      name: 'Session 2.0',
      focus: const Value('30 minute session'),
      durationMinutes: 31,
      volumeLoad: 50008,
      adjustedVolumeLoad: 50540,
      workRatio: 1.056,
      adjustedWorkRatio: 1.067,
      requirements: const Value('30 minute work load'),
      notes: const Value('Work towards front shoulder closer in line to front of body'),
      sortOrder: const Value(20),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 10,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 5,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 3,
        reps: 5,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 5,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'fast_movement_both',
        exerciseOrder: 6,
        reps: 5,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('10x2s. Big movements from crunched in to full extension. Try to maintain line'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 7,
        reps: 1,
        workSeconds: 30,
        restSeconds: 30,
      ),
    ],
  );
}

// =============================================================================
// SESSION 2.1 - 30 minutes with movements
// =============================================================================
OlySessionSeed _session21() {
  const sessionId = 'session_2.1';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '2.1',
      name: 'Session 2.1',
      focus: const Value('30 minutes with movements'),
      durationMinutes: 31,
      volumeLoad: 48412,
      adjustedVolumeLoad: 52814,
      workRatio: 0.984,
      adjustedWorkRatio: 1.073,
      requirements: const Value('30 minute work load'),
      notes: const Value('Work towards front shoulder closer in line to front of body'),
      sortOrder: const Value(21),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 5,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 5,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 3,
        reps: 5,
        workSeconds: 25,
        restSeconds: 30,
        details: const Value('5x5s movement off front. To full extension'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 4,
        reps: 4,
        workSeconds: 25,
        restSeconds: 25,
        details: const Value('5x5s 1cm each forward and back'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 25,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 7,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('3x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'fast_movement_both',
        exerciseOrder: 8,
        reps: 5,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('10x2s. Big movements from crunched in to full extension. Try to maintain line'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 9,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('3x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_10',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 10,
        reps: 1,
        workSeconds: 30,
        restSeconds: 30,
      ),
    ],
  );
}

// =============================================================================
// SESSION 2.2 - Slight increase
// =============================================================================
OlySessionSeed _session22() {
  const sessionId = 'session_2.2';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '2.2',
      name: 'Session 2.2',
      focus: const Value('Slight increase'),
      durationMinutes: 29,
      volumeLoad: 50806,
      adjustedVolumeLoad: 54211,
      workRatio: 1.192,
      adjustedWorkRatio: 1.272,
      requirements: const Value('Be comfortable with S2.2'),
      sortOrder: const Value(22),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 3,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('2x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 4,
        reps: 5,
        workSeconds: 30,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 5,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 6,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('3x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 7,
        reps: 3,
        workSeconds: 30,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'fast_movement_both',
        exerciseOrder: 8,
        reps: 8,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('10x2s fast movement'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 9,
        reps: 4,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_10',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 10,
        reps: 1,
        workSeconds: 75,
        restSeconds: 1,
        details: const Value('Hold as long as you can'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 2.3 - Movement control
// =============================================================================
OlySessionSeed _session23() {
  const sessionId = 'session_2.3';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '2.3',
      name: 'Session 2.3',
      focus: const Value('Movement control'),
      durationMinutes: 30,
      volumeLoad: 52136,
      adjustedVolumeLoad: 54583,
      workRatio: 1.223,
      adjustedWorkRatio: 1.281,
      requirements: const Value('Be comfortable with S2.2'),
      sortOrder: const Value(23),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 3,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 30,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 4,
        reps: 3,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('2x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 6,
        reps: 3,
        workSeconds: 30,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 7,
        reps: 2,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 8,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('3x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 9,
        reps: 3,
        workSeconds: 30,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_10',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'fast_movement_both',
        exerciseOrder: 10,
        reps: 8,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('10x2s fast movement'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_11',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 11,
        reps: 1,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('3x10s Slow movement'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_12',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 12,
        reps: 3,
        workSeconds: 25,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_13',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 13,
        reps: 1,
        workSeconds: 75,
        restSeconds: 1,
        details: const Value('Hold as long as you can'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 2.4 - Movement then ratio change
// =============================================================================
OlySessionSeed _session24() {
  const sessionId = 'session_2.4';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '2.4',
      name: 'Session 2.4',
      focus: const Value('Movement then ratio change'),
      durationMinutes: 31,
      volumeLoad: 54530,
      adjustedVolumeLoad: 57243,
      workRatio: 1.212,
      adjustedWorkRatio: 1.272,
      requirements: const Value('Be comfortable with S2.2'),
      sortOrder: const Value(24),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 2,
        reps: 2,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('2x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'fast_movement_both',
        exerciseOrder: 3,
        reps: 2,
        workSeconds: 20,
        restSeconds: 25,
        details: const Value('10x2s fast movement'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'extend_front_movement',
        exerciseOrder: 4,
        reps: 2,
        workSeconds: 20,
        restSeconds: 25,
        details: const Value('Push arm forward 4x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_end_movement',
        exerciseOrder: 5,
        reps: 2,
        workSeconds: 20,
        restSeconds: 25,
        details: const Value('4x5s 1cm each forward and back'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 6,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('3x10s Slow movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 7,
        reps: 3,
        workSeconds: 30,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 8,
        reps: 1,
        workSeconds: 30,
        restSeconds: 15,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 9,
        reps: 1,
        workSeconds: 30,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_10',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 10,
        reps: 3,
        workSeconds: 25,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_11',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 11,
        reps: 5,
        workSeconds: 15,
        restSeconds: 10,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_12',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 12,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_13',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 13,
        reps: 2,
        workSeconds: 30,
        restSeconds: 15,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_14',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 14,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_15',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'full_front_extension',
        exerciseOrder: 15,
        reps: 3,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('Hold front extended far as possible'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_16',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'long_hold',
        exerciseOrder: 16,
        reps: 1,
        workSeconds: 85,
        restSeconds: 1,
        details: const Value('Hold as long as you can'),
      ),
    ],
  );
}

// =============================================================================
// SESSION 2.5 - Aiming intro
// =============================================================================
OlySessionSeed _session25() {
  const sessionId = 'session_2.5';
  return OlySessionSeed(
    template: OlySessionTemplatesCompanion.insert(
      id: sessionId,
      version: '2.5',
      name: 'Session 2.5',
      focus: const Value('Aiming intro'),
      durationMinutes: 30,
      volumeLoad: 47348,
      adjustedVolumeLoad: 55488,
      workRatio: 0.978,
      adjustedWorkRatio: 1.146,
      requirements: const Value('Be comfortable with S1.5, 1.6'),
      notes: const Value('Aimed expansion needs strong focus on stability of aim.'),
      sortOrder: const Value(25),
    ),
    exercises: [
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_1',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 1,
        reps: 3,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_2',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 2,
        reps: 2,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_3',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'front_expansion_aimed',
        exerciseOrder: 3,
        reps: 3,
        workSeconds: 20,
        restSeconds: 30,
        details: const Value('4x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_4',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'back_expansion_aimed',
        exerciseOrder: 4,
        reps: 3,
        workSeconds: 20,
        restSeconds: 30,
        details: const Value('4x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_5',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 5,
        reps: 3,
        workSeconds: 30,
        restSeconds: 25,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_6',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'both_sides_expansion_aimed',
        exerciseOrder: 6,
        reps: 5,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('4x5s'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_7',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 7,
        reps: 3,
        workSeconds: 30,
        restSeconds: 25,
        details: const Value('Focus on extension of front arm'),
        intensityOverride: const Value(1.3),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_8',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 8,
        reps: 3,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_9',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 9,
        reps: 5,
        workSeconds: 30,
        restSeconds: 30,
        details: const Value('Big, balanced movement both sides'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_10',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 10,
        reps: 2,
        workSeconds: 20,
        restSeconds: 20,
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_11',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'slow_movement',
        exerciseOrder: 11,
        reps: 3,
        workSeconds: 20,
        restSeconds: 20,
        details: const Value('3x10s Slow steady expansion'),
      ),
      OlySessionExercisesCompanion.insert(
        id: '${sessionId}_12',
        sessionTemplateId: sessionId,
        exerciseTypeId: 'static',
        exerciseOrder: 12,
        reps: 2,
        workSeconds: 30,
        restSeconds: 30,
      ),
    ],
  );
}
