import 'package:drift/drift.dart';
import 'database.dart';

/// All standard round types for WA, AGB, and NFAA
/// This is kept separate from database.dart for readability

List<RoundTypesCompanion> getAllRoundTypesSeed() {
  return [
    // =========================================================================
    // WA INDOOR
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'wa_18_60',
      name: 'WA 18m (60 arrows)',
      category: 'wa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_18_30',
      name: 'WA 18m (30 arrows)',
      category: 'wa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 10,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_18_trispot',
      name: 'WA 18m Tri-Spot (60 arrows)',
      category: 'wa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(3),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_25_60',
      name: 'WA 25m (60 arrows)',
      category: 'wa_indoor',
      distance: 25,
      faceSize: 60,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // WA OUTDOOR
    // =========================================================================
    // WA 720 rounds
    RoundTypesCompanion.insert(
      id: 'wa_720_70m',
      name: 'WA 720 (70m)',
      category: 'wa_outdoor',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_60m',
      name: 'WA 720 (60m)',
      category: 'wa_outdoor',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_50m',
      name: 'WA 720 (50m)',
      category: 'wa_outdoor',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_40m',
      name: 'WA 720 (40m)',
      category: 'wa_outdoor',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_30m',
      name: 'WA 720 (30m)',
      category: 'wa_outdoor',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // WA 1440 (FITA) rounds
    RoundTypesCompanion.insert(
      id: 'wa_1440_90m',
      name: 'WA 1440 (90m)',
      category: 'wa_outdoor',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_1440_70m',
      name: 'WA 1440 (70m)',
      category: 'wa_outdoor',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_1440_60m',
      name: 'WA 1440 (60m)',
      category: 'wa_outdoor',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_1440_50m',
      name: 'WA 1440 (50m - Cadet)',
      category: 'wa_outdoor',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // AGB IMPERIAL OUTDOOR
    // =========================================================================
    // York / Hereford / Bristol series
    RoundTypesCompanion.insert(
      id: 'york',
      name: 'York',
      category: 'agb_imperial',
      distance: 100, // yards, longest distance
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12, // 72 arrows total (24@100, 24@80, 24@60)
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'hereford',
      name: 'Hereford',
      category: 'agb_imperial',
      distance: 80,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_1',
      name: 'Bristol I',
      category: 'agb_imperial',
      distance: 80,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_2',
      name: 'Bristol II',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_3',
      name: 'Bristol III',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_4',
      name: 'Bristol IV',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_5',
      name: 'Bristol V',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // St George / Albion / Windsor series
    RoundTypesCompanion.insert(
      id: 'st_george',
      name: 'St George',
      category: 'agb_imperial',
      distance: 100,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6, // 36 arrows
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'albion',
      name: 'Albion',
      category: 'agb_imperial',
      distance: 80,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'windsor',
      name: 'Windsor',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Short series
    RoundTypesCompanion.insert(
      id: 'short_windsor',
      name: 'Short Windsor',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'junior_windsor',
      name: 'Junior Windsor',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_junior_windsor',
      name: 'Short Junior Windsor',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // National series
    RoundTypesCompanion.insert(
      id: 'national',
      name: 'National',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8, // 48 arrows
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_national',
      name: 'Short National',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8,
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'junior_national',
      name: 'Junior National',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8,
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_junior_national',
      name: 'Short Junior National',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8,
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Western series
    RoundTypesCompanion.insert(
      id: 'western',
      name: 'Western',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8,
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_western',
      name: 'Short Western',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8,
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'junior_western',
      name: 'Junior Western',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8,
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_junior_western',
      name: 'Short Junior Western',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8,
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // American series
    RoundTypesCompanion.insert(
      id: 'american',
      name: 'American',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 5, // 30 arrows per distance, 90 total
      maxScore: 810,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_american',
      name: 'Short American',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 5,
      maxScore: 810,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Long/Short Warwick
    RoundTypesCompanion.insert(
      id: 'long_warwick',
      name: 'Long Warwick',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 4, // 24 arrows per distance
      maxScore: 432,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'warwick',
      name: 'Warwick',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 4,
      maxScore: 432,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_warwick',
      name: 'Short Warwick',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 4,
      maxScore: 432,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // AGB METRIC OUTDOOR
    // =========================================================================
    // Metric rounds (WA style distances in metric)
    RoundTypesCompanion.insert(
      id: 'metric_1',
      name: 'Metric I',
      category: 'agb_metric',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_2',
      name: 'Metric II',
      category: 'agb_metric',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_3',
      name: 'Metric III',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_4',
      name: 'Metric IV',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_5',
      name: 'Metric V',
      category: 'agb_metric',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Half Metric rounds
    RoundTypesCompanion.insert(
      id: 'half_metric_1',
      name: 'Half Metric I',
      category: 'agb_metric',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_2',
      name: 'Half Metric II',
      category: 'agb_metric',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_3',
      name: 'Half Metric III',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_4',
      name: 'Half Metric IV',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_5',
      name: 'Half Metric V',
      category: 'agb_metric',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Long Metric rounds
    RoundTypesCompanion.insert(
      id: 'long_metric_1',
      name: 'Long Metric I (Gents)',
      category: 'agb_metric',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_2',
      name: 'Long Metric II (Ladies)',
      category: 'agb_metric',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_3',
      name: 'Long Metric III',
      category: 'agb_metric',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_4',
      name: 'Long Metric IV',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_5',
      name: 'Long Metric V',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Short Metric rounds
    RoundTypesCompanion.insert(
      id: 'short_metric_1',
      name: 'Short Metric I',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_2',
      name: 'Short Metric II',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_3',
      name: 'Short Metric III',
      category: 'agb_metric',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_4',
      name: 'Short Metric IV',
      category: 'agb_metric',
      distance: 20,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_5',
      name: 'Short Metric V',
      category: 'agb_metric',
      distance: 15,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // AGB INDOOR
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'portsmouth',
      name: 'Portsmouth',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 60,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'worcester',
      name: 'Worcester',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 41, // 16 inch face
      arrowsPerEnd: 5,
      totalEnds: 12,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'vegas_300',
      name: 'Vegas 300',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 10,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bray_1',
      name: 'Bray I',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 6,
      totalEnds: 4, // 2.5 dozen
      maxScore: 270,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bray_2',
      name: 'Bray II',
      category: 'agb_indoor',
      distance: 23,
      faceSize: 40,
      arrowsPerEnd: 6,
      totalEnds: 4,
      maxScore: 270,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'stafford',
      name: 'Stafford',
      category: 'agb_indoor',
      distance: 27,
      faceSize: 80,
      arrowsPerEnd: 3,
      totalEnds: 24,
      maxScore: 720,
      isIndoor: true,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // NFAA INDOOR
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'nfaa_300',
      name: 'NFAA 300 Indoor',
      category: 'nfaa_indoor',
      distance: 18, // 20 yards
      faceSize: 40,
      arrowsPerEnd: 5,
      totalEnds: 12,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_vegas',
      name: 'NFAA Vegas (Las Vegas)',
      category: 'nfaa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 10,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_indoor_trispot',
      name: 'NFAA Indoor Tri-Spot',
      category: 'nfaa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(3),
    ),

    // =========================================================================
    // NFAA FIELD
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'nfaa_field_28',
      name: 'NFAA Field Round (28 targets)',
      category: 'nfaa_field',
      distance: 80, // Mixed distances
      faceSize: 65, // Various face sizes
      arrowsPerEnd: 4,
      totalEnds: 28,
      maxScore: 560, // 20 points max per target
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_hunter_28',
      name: 'NFAA Hunter Round (28 targets)',
      category: 'nfaa_field',
      distance: 70,
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 28,
      maxScore: 560,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_animal_28',
      name: 'NFAA Animal Round (28 targets)',
      category: 'nfaa_field',
      distance: 60,
      faceSize: 65,
      arrowsPerEnd: 3, // First arrow bonus scoring
      totalEnds: 28,
      maxScore: 560,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_field_14',
      name: 'NFAA Field Round (14 targets)',
      category: 'nfaa_field',
      distance: 80,
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 14,
      maxScore: 280,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_hunter_14',
      name: 'NFAA Hunter Round (14 targets)',
      category: 'nfaa_field',
      distance: 70,
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 14,
      maxScore: 280,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // PRACTICE
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'practice_indoor_3',
      name: 'Practice Indoor (3 arrows)',
      category: 'practice',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 99,
      maxScore: 2970,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'practice_indoor_5',
      name: 'Practice Indoor (5 arrows)',
      category: 'practice',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 5,
      totalEnds: 99,
      maxScore: 4950,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'practice_outdoor_6',
      name: 'Practice Outdoor (6 arrows)',
      category: 'practice',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 99,
      maxScore: 5940,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'practice_outdoor_3',
      name: 'Practice Outdoor (3 arrows)',
      category: 'practice',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 3,
      totalEnds: 99,
      maxScore: 2970,
      isIndoor: false,
      faceCount: const Value(1),
    ),
  ];
}
