import 'package:drift/drift.dart';
import 'database.dart';

/// All standard round types for WA, AGB, and NFAA
/// This is kept separate from database.dart for readability

List<RoundTypesCompanion> getAllRoundTypesSeed() {
  return [
    // =========================================================================
    // WA INDOOR
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'wa_18_60',
      name: 'WA 18m (60 arrows)',
      category: 'wa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_18_30',
      name: 'WA 18m (30 arrows)',
      category: 'wa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 10,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_18_trispot',
      name: 'WA 18m Tri-Spot (60 arrows)',
      category: 'wa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(3),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_25_60',
      name: 'WA 25m (60 arrows)',
      category: 'wa_indoor',
      distance: 25,
      faceSize: 60,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // WA OUTDOOR
    // =========================================================================
    // WA 720 rounds
    RoundTypesCompanion.insert(
      id: 'wa_720_70m',
      name: 'WA 720 (70m)',
      category: 'wa_outdoor',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_60m',
      name: 'WA 720 (60m)',
      category: 'wa_outdoor',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_50m',
      name: 'WA 720 (50m)',
      category: 'wa_outdoor',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_40m',
      name: 'WA 720 (40m)',
      category: 'wa_outdoor',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_720_30m',
      name: 'WA 720 (30m)',
      category: 'wa_outdoor',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 720,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // WA 1440 (FITA) rounds - 4 distances, 36 arrows each = 144 total = 24 ends
    // Face sizes: 122cm at long distances, 80cm at 50m and 30m
    RoundTypesCompanion.insert(
      id: 'wa_1440_90m',
      name: 'WA 1440 (90m)',
      category: 'wa_outdoor',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
      distanceLegs: const Value('[{"distance":90,"unit":"m","arrowCount":36},{"distance":70,"unit":"m","arrowCount":36},{"distance":50,"unit":"m","arrowCount":36,"faceSize":80},{"distance":30,"unit":"m","arrowCount":36,"faceSize":80}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_1440_70m',
      name: 'WA 1440 (70m)',
      category: 'wa_outdoor',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
      distanceLegs: const Value('[{"distance":70,"unit":"m","arrowCount":36},{"distance":60,"unit":"m","arrowCount":36},{"distance":50,"unit":"m","arrowCount":36,"faceSize":80},{"distance":30,"unit":"m","arrowCount":36,"faceSize":80}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_1440_60m',
      name: 'WA 1440 (60m)',
      category: 'wa_outdoor',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
      distanceLegs: const Value('[{"distance":60,"unit":"m","arrowCount":36},{"distance":50,"unit":"m","arrowCount":36},{"distance":40,"unit":"m","arrowCount":36,"faceSize":80},{"distance":30,"unit":"m","arrowCount":36,"faceSize":80}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'wa_1440_50m',
      name: 'WA 1440 (50m - Cadet)',
      category: 'wa_outdoor',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24,
      maxScore: 1440,
      isIndoor: false,
      faceCount: const Value(1),
      distanceLegs: const Value('[{"distance":50,"unit":"m","arrowCount":36},{"distance":40,"unit":"m","arrowCount":36},{"distance":30,"unit":"m","arrowCount":36,"faceSize":80},{"distance":20,"unit":"m","arrowCount":36,"faceSize":80}]'),
    ),

    // =========================================================================
    // AGB IMPERIAL OUTDOOR (5-zone scoring: 9-7-5-3-1 by color)
    // Multi-distance rounds have distanceLegs defining each distance segment.
    // =========================================================================
    // York / Hereford / Bristol series (72/48/24 arrows = 144 total = 24 ends)
    RoundTypesCompanion.insert(
      id: 'york',
      name: 'York',
      category: 'agb_imperial',
      distance: 100, // yards, longest distance (used for display/categorization)
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24, // 144 arrows: 72@100yd + 48@80yd + 24@60yd
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":100,"unit":"yd","arrowCount":72},{"distance":80,"unit":"yd","arrowCount":48},{"distance":60,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'hereford',
      name: 'Hereford',
      category: 'agb_imperial',
      distance: 80,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24, // 144 arrows: 72@80yd + 48@60yd + 24@50yd
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":80,"unit":"yd","arrowCount":72},{"distance":60,"unit":"yd","arrowCount":48},{"distance":50,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_1',
      name: 'Bristol I',
      category: 'agb_imperial',
      distance: 80,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24, // 144 arrows: 72@80yd + 48@60yd + 24@50yd
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":80,"unit":"yd","arrowCount":72},{"distance":60,"unit":"yd","arrowCount":48},{"distance":50,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_2',
      name: 'Bristol II',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24, // 144 arrows: 72@60yd + 48@50yd + 24@40yd
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":60,"unit":"yd","arrowCount":72},{"distance":50,"unit":"yd","arrowCount":48},{"distance":40,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_3',
      name: 'Bristol III',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24, // 144 arrows: 72@50yd + 48@40yd + 24@30yd
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":50,"unit":"yd","arrowCount":72},{"distance":40,"unit":"yd","arrowCount":48},{"distance":30,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_4',
      name: 'Bristol IV',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24, // 144 arrows: 72@40yd + 48@30yd + 24@20yd
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":40,"unit":"yd","arrowCount":72},{"distance":30,"unit":"yd","arrowCount":48},{"distance":20,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'bristol_5',
      name: 'Bristol V',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 24, // 144 arrows: 72@30yd + 48@20yd + 24@10yd
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":30,"unit":"yd","arrowCount":72},{"distance":20,"unit":"yd","arrowCount":48},{"distance":10,"unit":"yd","arrowCount":24}]'),
    ),

    // St George / Albion / Windsor series (36/36/36 arrows = 108 total = 18 ends)
    RoundTypesCompanion.insert(
      id: 'st_george',
      name: 'St George',
      category: 'agb_imperial',
      distance: 100,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 18, // 108 arrows: 36@100yd + 36@80yd + 36@60yd
      maxScore: 972,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":100,"unit":"yd","arrowCount":36},{"distance":80,"unit":"yd","arrowCount":36},{"distance":60,"unit":"yd","arrowCount":36}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'albion',
      name: 'Albion',
      category: 'agb_imperial',
      distance: 80,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 18, // 108 arrows: 36@80yd + 36@60yd + 36@50yd
      maxScore: 972,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":80,"unit":"yd","arrowCount":36},{"distance":60,"unit":"yd","arrowCount":36},{"distance":50,"unit":"yd","arrowCount":36}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'windsor',
      name: 'Windsor',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 18, // 108 arrows: 36@60yd + 36@50yd + 36@40yd
      maxScore: 972,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":60,"unit":"yd","arrowCount":36},{"distance":50,"unit":"yd","arrowCount":36},{"distance":40,"unit":"yd","arrowCount":36}]'),
    ),

    // Short Windsor series (36/36/36 arrows = 108 total = 18 ends)
    RoundTypesCompanion.insert(
      id: 'short_windsor',
      name: 'Short Windsor',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 18, // 108 arrows: 36@50yd + 36@40yd + 36@30yd
      maxScore: 972,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":50,"unit":"yd","arrowCount":36},{"distance":40,"unit":"yd","arrowCount":36},{"distance":30,"unit":"yd","arrowCount":36}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'junior_windsor',
      name: 'Junior Windsor',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 18, // 108 arrows: 36@40yd + 36@30yd + 36@20yd
      maxScore: 972,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":40,"unit":"yd","arrowCount":36},{"distance":30,"unit":"yd","arrowCount":36},{"distance":20,"unit":"yd","arrowCount":36}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'short_junior_windsor',
      name: 'Short Junior Windsor',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 18, // 108 arrows: 36@30yd + 36@20yd + 36@10yd
      maxScore: 972,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":30,"unit":"yd","arrowCount":36},{"distance":20,"unit":"yd","arrowCount":36},{"distance":10,"unit":"yd","arrowCount":36}]'),
    ),

    // National series (48/24 arrows = 72 total = 12 ends)
    RoundTypesCompanion.insert(
      id: 'long_national',
      name: 'Long National',
      category: 'agb_imperial',
      distance: 80,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12, // 72 arrows: 48@80yd + 24@60yd
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":80,"unit":"yd","arrowCount":48},{"distance":60,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'national',
      name: 'National',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12, // 72 arrows: 48@60yd + 24@50yd
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":60,"unit":"yd","arrowCount":48},{"distance":50,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'short_national',
      name: 'Short National',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12, // 72 arrows: 48@50yd + 24@40yd
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":50,"unit":"yd","arrowCount":48},{"distance":40,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'junior_national',
      name: 'Junior National',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12, // 72 arrows: 48@40yd + 24@30yd
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":40,"unit":"yd","arrowCount":48},{"distance":30,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'short_junior_national',
      name: 'Short Junior National',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12, // 72 arrows: 48@30yd + 24@20yd
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":30,"unit":"yd","arrowCount":48},{"distance":20,"unit":"yd","arrowCount":24}]'),
    ),

    // Western series (48/48 arrows = 96 total = 16 ends)
    RoundTypesCompanion.insert(
      id: 'western',
      name: 'Western',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 16, // 96 arrows: 48@60yd + 48@50yd
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":60,"unit":"yd","arrowCount":48},{"distance":50,"unit":"yd","arrowCount":48}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'short_western',
      name: 'Short Western',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 16, // 96 arrows: 48@50yd + 48@40yd
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":50,"unit":"yd","arrowCount":48},{"distance":40,"unit":"yd","arrowCount":48}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'junior_western',
      name: 'Junior Western',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 16, // 96 arrows: 48@40yd + 48@30yd
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":40,"unit":"yd","arrowCount":48},{"distance":30,"unit":"yd","arrowCount":48}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'short_junior_western',
      name: 'Short Junior Western',
      category: 'agb_imperial',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 16, // 96 arrows: 48@30yd + 48@20yd
      maxScore: 864,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":30,"unit":"yd","arrowCount":48},{"distance":20,"unit":"yd","arrowCount":48}]'),
    ),

    // American series (30/30/30 arrows = 90 total = 15 ends)
    RoundTypesCompanion.insert(
      id: 'american',
      name: 'American',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 15, // 90 arrows: 30@60yd + 30@50yd + 30@40yd
      maxScore: 810,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":60,"unit":"yd","arrowCount":30},{"distance":50,"unit":"yd","arrowCount":30},{"distance":40,"unit":"yd","arrowCount":30}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'short_american',
      name: 'Short American',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 15, // 90 arrows: 30@50yd + 30@40yd + 30@30yd
      maxScore: 810,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":50,"unit":"yd","arrowCount":30},{"distance":40,"unit":"yd","arrowCount":30},{"distance":30,"unit":"yd","arrowCount":30}]'),
    ),

    // Warwick series (24/24 arrows = 48 total = 8 ends)
    RoundTypesCompanion.insert(
      id: 'long_warwick',
      name: 'Long Warwick',
      category: 'agb_imperial',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8, // 48 arrows: 24@60yd + 24@50yd
      maxScore: 432,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":60,"unit":"yd","arrowCount":24},{"distance":50,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'warwick',
      name: 'Warwick',
      category: 'agb_imperial',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8, // 48 arrows: 24@50yd + 24@40yd
      maxScore: 432,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":50,"unit":"yd","arrowCount":24},{"distance":40,"unit":"yd","arrowCount":24}]'),
    ),
    RoundTypesCompanion.insert(
      id: 'short_warwick',
      name: 'Short Warwick',
      category: 'agb_imperial',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 8, // 48 arrows: 24@40yd + 24@30yd
      maxScore: 432,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
      distanceLegs: const Value('[{"distance":40,"unit":"yd","arrowCount":24},{"distance":30,"unit":"yd","arrowCount":24}]'),
    ),

    // =========================================================================
    // AGB METRIC OUTDOOR
    // =========================================================================
    // Metric rounds (WA style distances in metric)
    RoundTypesCompanion.insert(
      id: 'metric_1',
      name: 'Metric I',
      category: 'agb_metric',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_2',
      name: 'Metric II',
      category: 'agb_metric',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_3',
      name: 'Metric III',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_4',
      name: 'Metric IV',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'metric_5',
      name: 'Metric V',
      category: 'agb_metric',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 12,
      maxScore: 1296,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Half Metric rounds
    RoundTypesCompanion.insert(
      id: 'half_metric_1',
      name: 'Half Metric I',
      category: 'agb_metric',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_2',
      name: 'Half Metric II',
      category: 'agb_metric',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    // 70m half round (36 arrows - used in head-to-heads and practice)
    RoundTypesCompanion.insert(
      id: 'half_metric_70m',
      name: '70m (36 arrows)',
      category: 'agb_metric',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 360,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_3',
      name: 'Half Metric III',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_4',
      name: 'Half Metric IV',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'half_metric_5',
      name: 'Half Metric V',
      category: 'agb_metric',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Long Metric rounds
    RoundTypesCompanion.insert(
      id: 'long_metric_1',
      name: 'Long Metric I (Gents)',
      category: 'agb_metric',
      distance: 90,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_2',
      name: 'Long Metric II (Ladies)',
      category: 'agb_metric',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_3',
      name: 'Long Metric III',
      category: 'agb_metric',
      distance: 60,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_4',
      name: 'Long Metric IV',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'long_metric_5',
      name: 'Long Metric V',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // Short Metric rounds
    RoundTypesCompanion.insert(
      id: 'short_metric_1',
      name: 'Short Metric I',
      category: 'agb_metric',
      distance: 50,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_2',
      name: 'Short Metric II',
      category: 'agb_metric',
      distance: 40,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_3',
      name: 'Short Metric III',
      category: 'agb_metric',
      distance: 30,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_4',
      name: 'Short Metric IV',
      category: 'agb_metric',
      distance: 20,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'short_metric_5',
      name: 'Short Metric V',
      category: 'agb_metric',
      distance: 15,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 6,
      maxScore: 648,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // AGB INDOOR
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'portsmouth',
      name: 'Portsmouth',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 60,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'worcester',
      name: 'Worcester',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 41, // 16 inch face
      arrowsPerEnd: 5,
      totalEnds: 12,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
      scoringType: const Value('worcester'), // Worcester uses 5-4-3-2-1 scoring
    ),
    RoundTypesCompanion.insert(
      id: 'vegas_300',
      name: 'Vegas 300',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 10,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bray_1',
      name: 'Bray I',
      category: 'agb_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 6,
      totalEnds: 4, // 2.5 dozen
      maxScore: 270,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'bray_2',
      name: 'Bray II',
      category: 'agb_indoor',
      distance: 23,
      faceSize: 40,
      arrowsPerEnd: 6,
      totalEnds: 4,
      maxScore: 270,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'stafford',
      name: 'Stafford',
      category: 'agb_indoor',
      distance: 27,
      faceSize: 80,
      arrowsPerEnd: 3,
      totalEnds: 24,
      maxScore: 720,
      isIndoor: true,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // NFAA INDOOR
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'nfaa_300',
      name: 'NFAA 300 Indoor',
      category: 'nfaa_indoor',
      distance: 18, // 20 yards
      faceSize: 40,
      arrowsPerEnd: 5,
      totalEnds: 12,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_vegas',
      name: 'NFAA Vegas (Las Vegas)',
      category: 'nfaa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 10,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_indoor_trispot',
      name: 'NFAA Indoor Tri-Spot',
      category: 'nfaa_indoor',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 20,
      maxScore: 600,
      isIndoor: true,
      faceCount: const Value(3),
    ),

    // =========================================================================
    // NFAA FIELD
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'nfaa_field_28',
      name: 'NFAA Field Round (28 targets)',
      category: 'nfaa_field',
      distance: 80, // Mixed distances
      faceSize: 65, // Various face sizes
      arrowsPerEnd: 4,
      totalEnds: 28,
      maxScore: 560, // 20 points max per target
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_hunter_28',
      name: 'NFAA Hunter Round (28 targets)',
      category: 'nfaa_field',
      distance: 70,
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 28,
      maxScore: 560,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_animal_28',
      name: 'NFAA Animal Round (28 targets)',
      category: 'nfaa_field',
      distance: 60,
      faceSize: 65,
      arrowsPerEnd: 3, // First arrow bonus scoring
      totalEnds: 28,
      maxScore: 560,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_field_14',
      name: 'NFAA Field Round (14 targets)',
      category: 'nfaa_field',
      distance: 80,
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 14,
      maxScore: 280,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'nfaa_hunter_14',
      name: 'NFAA Hunter Round (14 targets)',
      category: 'nfaa_field',
      distance: 70,
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 14,
      maxScore: 280,
      isIndoor: false,
      faceCount: const Value(1),
    ),

    // =========================================================================
    // IFAA (International Field Archery Association)
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'ifaa_field',
      name: 'IFAA Field Round',
      category: 'ifaa_field',
      distance: 80, // Mixed distances 6.7-80 yards
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 28,
      maxScore: 560, // 5-4-3 scoring (5 max per arrow)
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
    ),
    RoundTypesCompanion.insert(
      id: 'ifaa_hunter',
      name: 'IFAA Hunter Round',
      category: 'ifaa_field',
      distance: 70, // Mixed distances 14-70 yards
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 28,
      maxScore: 560,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
    ),
    RoundTypesCompanion.insert(
      id: 'ifaa_expert',
      name: 'IFAA Expert Round',
      category: 'ifaa_field',
      distance: 60, // 60 yards fixed
      faceSize: 41, // Worcester-style face
      arrowsPerEnd: 5,
      totalEnds: 20,
      maxScore: 500,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
    ),
    RoundTypesCompanion.insert(
      id: 'ifaa_flint',
      name: 'IFAA Flint Round',
      category: 'ifaa_field',
      distance: 60, // Mixed distances, walk-up
      faceSize: 65,
      arrowsPerEnd: 4,
      totalEnds: 28,
      maxScore: 560,
      isIndoor: false,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
    ),
    RoundTypesCompanion.insert(
      id: 'ifaa_indoor',
      name: 'IFAA Indoor',
      category: 'ifaa_indoor',
      distance: 10, // 10 yards (9.14m)
      faceSize: 41, // Worcester-style face
      arrowsPerEnd: 5,
      totalEnds: 12,
      maxScore: 300,
      isIndoor: true,
      faceCount: const Value(1),
      scoringType: const Value('5-zone'),
    ),

    // =========================================================================
    // PRACTICE
    // =========================================================================
    RoundTypesCompanion.insert(
      id: 'practice_indoor_3',
      name: 'Practice Indoor (3 arrows)',
      category: 'practice',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 3,
      totalEnds: 99,
      maxScore: 2970,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'practice_indoor_5',
      name: 'Practice Indoor (5 arrows)',
      category: 'practice',
      distance: 18,
      faceSize: 40,
      arrowsPerEnd: 5,
      totalEnds: 99,
      maxScore: 4950,
      isIndoor: true,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'practice_outdoor_6',
      name: 'Practice Outdoor (6 arrows)',
      category: 'practice',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 6,
      totalEnds: 99,
      maxScore: 5940,
      isIndoor: false,
      faceCount: const Value(1),
    ),
    RoundTypesCompanion.insert(
      id: 'practice_outdoor_3',
      name: 'Practice Outdoor (3 arrows)',
      category: 'practice',
      distance: 70,
      faceSize: 122,
      arrowsPerEnd: 3,
      totalEnds: 99,
      maxScore: 2970,
      isIndoor: false,
      faceCount: const Value(1),
    ),
  ];
}
